spring.application.name=Assignment7
spring.datasource.url = jdbc:postgresql://postgres-db:5432/employeedb
spring.datasource.username = postgres
spring.datasource.password = Shreya29#
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085
